### ISSUE TITLE
* should match zero or more characters

### ISSUE THREAD

**Issue by DaRosenberg** [fastwildcard/fastwildcard#1]
Thanks for a great library!

One question: in the readme you state:

> '*' matches 1 or more characters

Most common wildcard conventions interpret * as matching **zero** or more characters, not one or more.

Is the readme incorrect, or does it match the implementation?

**Comment by alexangas** [comment]
Thanks for your feedback!

You are indeed correct about all of the above. This is a bug... an unfortunate consequence of rushing something out the door while targeting a specific use case.

This will be addressed in the next release, and as it is a pretty major issue I will try to get that done in the next week or so (unless someone else raises their hand first). From that point on it will be necessary to use `?*` to get the current behaviour of `*`.

**Comment by DaRosenberg** [comment]
Sounds good! I'll be checking for the closure notification for this issue!

**Comment by alexangas** [comment]
@DaRosenberg Version 3.0.0 has been released that contains this fix! Thank you again for reporting it.

**Comment by DaRosenberg** [comment]
@alexangas Thanks for the heads-up! Just updated our code base!
